name: Deploy Docassemble to AWS Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Set up SSH public key
      run: echo "${{ secrets.LIGHTSAIL_PUBLIC_KEY }}" | base64 --decode > lightsail_key.pub

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform Configuration
      run: terraform apply -auto-approve

    - name: Setup SSH for Lightsail
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}" > ~/.ssh/lightsail.pem
        chmod 600 ~/.ssh/lightsail.pem

    - name: Get and Validate Lightsail Instance IP
      id: ip
      run: |
        # Get the IP and clean any extra output
        CLEAN_IP=$(terraform output -raw instance_ip | tr -d '\n')

        # Validate IP format
        if [[ $CLEAN_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Valid IP address: ${CLEAN_IP}"
          echo "LIGHTSAIL_IP=${CLEAN_IP}" >> "$GITHUB_ENV"
        else
          echo "Error: Invalid IP address format: ${CLEAN_IP}"
          echo "Raw terraform output:"
          terraform output
          exit 1
        fi

    - name: Wait for Instance Boot
      run: |
        echo "Waiting for instance to complete boot process..."
        sleep 60  # Wait for 60 seconds to ensure instance is ready

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightsail.pem ubuntu@${{ env.LIGHTSAIL_IP }} "echo Connected!"

    - name: Install Docker and Deploy Docassemble
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightsail.pem ubuntu@${{ env.LIGHTSAIL_IP }} '
          # Update system packages
          sudo apt update -y
          sudo apt upgrade -y

          # Install Docker dependencies
          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common

          # Add Docker GPG key and repository
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

          # Install Docker
          sudo apt update -y
          sudo apt install -y docker-ce docker-ce-cli containerd.io

          # Pull Docassemble image
          sudo docker pull sylvia98/docassemble:latest

          # Stop and remove existing container if it exists
          sudo docker stop docassemble 2>/dev/null || true
          sudo docker rm docassemble 2>/dev/null || true

          # Run new container
          sudo docker run -d -p 80:80 --name docassemble sylvia98/docassemble:latest
        '

    - name: Print Instance Information
      run: |
        echo "Instance IP: $(terraform output -raw instance_ip)"
        echo "Instance Name: $(terraform output -raw instance_name)"
        echo "Key Pair Name: $(terraform output -raw key_pair_name)"