name: Deploy Docassemble to AWS Lightsail

on:
  push:
    branches:
      - master  # Trigger the workflow when there's a push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Set the runner environment to Ubuntu (default GitHub runner)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repo to the GitHub Actions runner

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1  # Set up Terraform to manage infrastructure
      with:
        terraform_version: 1.0.0  # Define the Terraform version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1  # Set AWS credentials for Terraform
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'  # Define the AWS region

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform Configuration
      run: terraform apply -auto-approve

    - name: Install Docker and Pull Docassemble Image
      run: |
        # Update package list and upgrade existing packages
        sudo apt update -y
        sudo apt upgrade -y

        # Install required packages and dependencies for Docker
        sudo apt install -y apt-transport-https ca-certificates curl software-properties-common

        # Add Docker’s official GPG key
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

        # Set up the Docker repository
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

        # Update package list again after adding Docker's repo
        sudo apt update -y

        # Install Docker
        sudo apt install -y docker-ce docker-ce-cli containerd.io

        # Pull the Docassemble image (only if it isn't already pulled)
        sudo docker pull sylvia98/docassemble:latest

        # Run the Docassemble container if not running
        sudo docker run -d -p 80:80 --name docassemble sylvia98/docassemble:latest

    - name: Add SSH private key to agent
      run: |
        echo "${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}" | ssh-add -

    - name: Deploy Docassemble
      run: |
        # SSH into Lightsail instance and deploy code
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.LIGHTSAIL_PUBLIC_IP }} << 'EOF'
          # If the directory doesn't exist, clone the repository from GitHub
          if [ ! -d "/home/ubuntu/docassemble" ]; then
            git clone https://github.com/SylviaKarani/docassemble.git /home/ubuntu/docassemble
          else
            # If the repo already exists, pull the latest changes
            cd /home/ubuntu/docassemble
            git pull origin main
          fi

          # If docassemble container is running, restart it
          if sudo docker ps -q -f name=docassemble; then
            sudo docker restart docassemble
          else
            # If docassemble container is not running, start it
            sudo docker run -d -p 80:80 --name docassemble sylvia98/docassemble:latest
          fi
        EOF
